export enum Socket {
    GET_ONLINE_USERS = "GET_ONLINE_USERS",
    ONLINE_USERS_LIST = "ONLINE_USERS_LIST",
    CHALLENGE_REQUEST = "CHALLENGE_REQUEST",
    APPROVE_CHALLENGE_REQUEST = "APPROVE_CHALLENGE_REQUEST",
    NEW_USER_CONNECTION = "NEW_USER_CONNECTION",
    DISCONNECT_USER = "DISCONNECT_USER",
    NEW_CHALLENGE_REQUEST = "NEW_CHALLENGE_REQUEST",
    START_GAME = "START_GAME",
    CONNECTION_ERROR = "CONNECTION_ERROR"
}
